### ISSUE TITLE
Defenseless Characters in Non-Defenseless Classes

### ISSUE THREAD

**Issue by i8sigmapi** [thane98/ignis#3]
I noticed this issue in the prologue with Ryoma's replacement, but since it's related to item-giving logic it seems likely it could appear in other places as well. A character in a promoted staff class (Great Master) generated with a 1-charge Lilith's Staff and no weapons, rendering them unable to fight.
Seed: 7633
Settings: same as in other issue I opened
Other Mods: Gay Fates, My Castle Join for Amiibo units

**Comment by i8sigmapi** [comment]
Also butler is being incorrectly treated as a capped at 40 class when characters get it as their assignment when it's actually a promoted class, leading to them being unable to gain any levels.

**Comment by thane98** [comment]
Looks like I need to curate the item list - lilith's staff should not be in the pool at all. Same applies to other restricted items like amiibo weapons.

I will look into the classification for butler/maid as well.

**Comment by i8sigmapi** [comment]
This was an ally, not player, unit that received the 1-charge staff instead of a weapon, just to clarify in case it's important. (The character later showed up in chapter 4 with a different 1-charge staff as well. If this carries over to enemy appearances as well it could have a significant effect on difficulty.)

As for the butler/maid, using the seed and settings provided should allow you to see the issue directly via the Gunter replacement. (Mods shouldn't be necessary though -- they were listed for purposes of clarity in case inconsistencies popped up.)

**Comment by thane98** [comment]
Very late to this, but I've added a fix: https://github.com/thane98/ignis/commit/dff126ee054d455bb1c2986592a421e7a22f8192#diff-420f8a03a0456a49334f047822f0ca9f95edf50177ef9c0daa8e817c9a6dc6efR110

This will try to give a class an extra weapon if they received a staff but have the ability to use something else.
