### ISSUE TITLE
Amiibo Weapon in Chest

### ISSUE THREAD

**Issue by SevenShanks** [thane98/ignis#4]
In A Vow Upheld (Birthright Chapter 7), I found Thoron in a chest. Thoron cannot be removed from whoever holds it (no convoy, no trading, etc.), so this basically results in a weapon permanently stuck in my unit's inventory, and I was forced to promote them to a tome user if I wanted to actually use that slot.
I _assume_ this is unintended behaviour. I don't know much about coding, but the two solutions I can think of are to either remove Amiibo items from the chest item pool when randomizing chest items, or to enable regularly trading/convoying them.

**Comment by thane98** [comment]
Thanks for the report. This should be fixed with https://github.com/thane98/ignis/commit/dff126ee054d455bb1c2986592a421e7a22f8192#diff-6d052b57a8160864e795f35478b2be94f4c58e16dab9344277f67841ca4b117aL1496
