### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by hosheep** [thane98/ignis#8]
hi, when trying to install ingis, i get the following:

Traceback (most recent call last):
  File "ignis\core\randomize_worker.py", line 34, in run
Exception: Failed to read data from stores.

Caused by:
    0: Failed to read data from store 'rom2'.
    1: File 'asset/ROM2.lz' does not exist.

not sure what to do to fix it?

**Comment by thane98** [comment]
This usually means that your ROM path is incorrect. Is your ROM path set to the root of an extracted RomFS (not romfs.bin)?
